# Generated by Django 3.2 on 2022-07-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('discussion', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='likes', to='user.CustomUser'),
        ),
    ]
