# Generated by Django 3.2 on 2022-07-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
